version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: open-finance-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: open-finance
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: open-finance-rabbit
    ports:
      - '5672:5672'   # AMQP
      - '15672:15672' # Management UI (guest/guest)
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

volumes:
  mongo_data:
  rabbit_data:
